name: Lint

on:
  push:
    paths:
      - '**.md'
      - '.github/workflows/md-lint.yml'
jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run mdl
      uses: actionshub/markdownlint@master
