name: Convert PDF to Markdown

on:
  push:
    paths:
    - '**.md'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: Create .pdfs
      uses: scottypate/md-to-pdf@v0.1.1
      env: {
        PDF_DIR: './pdfs'
      }
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .pdf files.
        PULL_REQUEST_TITLE: Add .pdf files.
        PULL_REQUEST_BRANCH: pdf-add
        PULL_REQUEST_BODY: :wave: Here are the .pdf files you requested.
        PULL_REQUEST_REVIEWERS: scottypate
